In [11]:
import torch as t
import torch.nn as nn

In [15]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim = 2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.W = nn.Parameter(t.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(t.FloatTensor(output_dim))

    def forward(self, x):
        #선형 변환 수행: y = wx + b
        y = t.matmul(x, self.W)+self.b
        return y

In [19]:
W = t.FloatTensor([i for i in range(1,7)]).reshape(3,2)
b = t.FloatTensor([2,2])
x = t.FloatTensor(4,3)

print(W, b, x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) tensor([2., 2.]) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [17]:
linear = MyLinear(3,2)
y = linear(x)

for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [18]:
#torch.nn에 구현된 선형 계층 사용하기

linear = nn.Linear(3, 2)
y = linear(x)

for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.1862, -0.4688, -0.0785],
        [ 0.0909, -0.2871,  0.0970]], requires_grad=True)
Parameter containing:
tensor([-0.4769,  0.4580], requires_grad=True)
