In [2]:
import torch as t

In [3]:
a = t.FloatTensor([[1,2],
                   [3,4]])
b = t.FloatTensor([[2,2],
                   [2,3]])

In [4]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[3., 4.],
        [5., 7.]])
tensor([[-1.,  0.],
        [ 1.,  1.]])
tensor([[ 2.,  4.],
        [ 6., 12.]])
tensor([[0.5000, 1.0000],
        [1.5000, 1.3333]])


In [5]:
print(a**b)
print(a==b)
print(a!=b)


tensor([[ 1.,  4.],
        [ 9., 64.]])
tensor([[False,  True],
        [False, False]])
tensor([[ True, False],
        [ True,  True]])


In [8]:
x = t.FloatTensor([[1,2],
                   [3,4]])
print(x.size())

torch.Size([2, 2])


In [9]:
a1 = t.FloatTensor([[1,2]])
a2 = t.FloatTensor([[3],
                    [4]])

print(a1.size(), a2.size())

torch.Size([1, 2]) torch.Size([2, 1])


In [10]:
print(a1+a2)

tensor([[4., 5.],
        [5., 6.]])


In [11]:
print((a1+a2).size())

torch.Size([2, 2])
