In [1]:
a = '2024'
b = '09'
print(a+b)

202409


In [2]:
n = int(input())
print(2050-n+1)

50


In [3]:
sum = 0
for i in range(1, 101):
    if (i % 7 == 0):
        sum += i
print(sum)

735


In [14]:
import numpy as np
x = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
print(x)

print(x[:,1::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 4]
 [7 9]]
