In [17]:
import numpy as np
arr = np.random.randint(10, size = 10)
print(arr)

[3 7 1 4 0 1 9 5 4 1]


In [18]:
print(np.sort(arr))

[0 1 1 1 3 4 4 5 7 9]


In [19]:
arr2 = np.random.randint(15, size = (3,4))
print(arr2)

[[ 3 10  7 12]
 [ 9 14 13 10]
 [ 8  8  5 14]]


In [20]:
print(np.sort(arr2, axis = 0))
print(np.argsort(arr2, axis = 0))

[[ 3  8  5 10]
 [ 8 10  7 12]
 [ 9 14 13 14]]
[[0 2 2 1]
 [2 0 0 0]
 [1 1 1 2]]


In [21]:
arr3 = np.arange(12)
print(arr3,"\n", arr3.ndim,"\n")
#차원을 늘려주는 reshape
arr3 = arr3.reshape((3,4))
print(arr3,"\n", arr3.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
 1 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 2


In [22]:
arr3.resize(4,3)
print(arr3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [23]:
arr3 = arr3.ravel()
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [24]:
arr3 = arr3.reshape(3,-1)
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
arr4 = np.array([1,2])
print(arr4, arr4.shape)
arr4 = np.expand_dims(arr4, axis = 1)
print(arr4, arr4.shape)

[1 2] (2,)
[[1]
 [2]] (2, 1)


In [42]:
arr4 = np.array([[1,2]])
print("arr4",arr4, arr4.shape, arr4.ndim)
arr4 = np.squeeze(arr4, axis = 0)
print("arr4",arr4, arr4.shape, arr4.ndim)

arr5 = np.array([[[1,2,3]]])
print("arr5",arr5, arr5.shape, arr5.ndim)
arr5 = np.squeeze(arr5)
print("arr5",arr5, arr5.shape, arr5.ndim)

arr4 [[1 2]] (1, 2) 2
arr4 [1 2] (2,) 1
arr5 [[[1 2 3]]] (1, 1, 3) 3
arr5 [1 2 3] (3,) 1


In [37]:
ar = np.arange(1,7).reshape(2,3)
ar2 = np.arange(7,13).reshape(2,3)

ar3 = np.vstack((ar,ar2))
print(ar3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#vsplit() => axis = 0을 기준으로한다.
#hsplit() => axis = 1을 기준으로 한다.
# 2차원 기준임

#